"""index.md (catalog) and log.md (append-only chronicle) helpers.

index.md is regenerated deterministically from the merged runbooks so it can never drift;
each line carries the signature keywords the chooser reads."""

from __future__ import annotations

import re

from judge.memory.schema import Runbook

INDEX_HEADER = """# Runbook index

One line per runbook: summary, services, error types. Regenerated by tooling on every merge;
do not edit by hand — edit the runbook's "Summary" section instead.

"""

LOG_HEADER = """# Incident log

Append-only. One event per line: `time | incident | fingerprint | service | severity | outcome | runbook`.
Lines labelled `candidate` = an incident class seen for the first time, no runbook yet.

"""

INDEX_LINE_RE = re.compile(
    r"^- \[(?P<title>[^\]]*)\]\(runbooks/(?P<id>[a-z0-9][a-z0-9-]*)\.md\)"
    r"(?: — (?P<summary>.*?))?(?: · services: (?P<services>[^·]*))?(?: · errors: (?P<errors>.*))?$"
)


def index_line(rb: Runbook) -> str:
    fm = rb.frontmatter
    services = ", ".join(fm.signatures.services) or "-"
    errors = ", ".join(fm.signatures.error_types) or "-"
    summary = rb.summary().replace("\n", " ") or "-"
    return f"- [{fm.title}](runbooks/{fm.id}.md) — {summary} · services: {services} · errors: {errors}"


DOCS_SECTION = """
## Service docs

Engineering docs the agent reads to diagnose incidents that no runbook covers (maintained by humans).

- [ShopLab architecture](architecture.md) — journeys, topology, dependencies, runtime config, metrics, safe actions
- [checkout](services/checkout.md) — payments: flag payment_v2, versions, pool, failure modes
- [search](services/search.md) — product search: worker health, shared database, failure modes
- [catalog](services/catalog.md) — product pages and avatars: critical vs secondary routes, failure modes
- [internal-batch](services/internal-batch.md) — internal nightly report job, failure modes
"""


def render_index(runbooks: list[Runbook]) -> str:
    """Runbook lines (regenerated) followed by the static service-docs section, which must survive regeneration."""
    lines = [index_line(rb) for rb in sorted(runbooks, key=lambda r: r.id)]
    return INDEX_HEADER + "\n".join(lines) + ("\n" if lines else "") + DOCS_SECTION


def parse_index(text: str) -> list[dict]:
    entries = []
    for line in (text or "").splitlines():
        m = INDEX_LINE_RE.match(line.strip())
        if m:
            d = m.groupdict()
            d["services"] = [s.strip() for s in (d.get("services") or "").split(",") if s.strip() and s.strip() != "-"]
            d["errors"] = [s.strip() for s in (d.get("errors") or "").split(",") if s.strip() and s.strip() != "-"]
            entries.append(d)
    return entries


def merge_log(main_text: str, proposal_text: str) -> str:
    """Union for an append-only file: keep main's lines in order, append proposal lines main lacks."""
    main_lines = (main_text or LOG_HEADER).rstrip("\n").split("\n")
    seen = set(main_lines)
    extra = [l for l in (proposal_text or "").rstrip("\n").split("\n") if l.strip() and l not in seen]
    return "\n".join(main_lines + extra) + "\n"
